site_name: Bugg documentation
site_url: https://sarabsethi.github.io/test-docs/
nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Hardware: hardware.md
  - Configuration: config.md
  - Audio: audio.md
  - Connectivity: connectivity.md
  - Power: power.md
  - Time: time.md
  - Troubleshooting: troubleshooting.md
  - Advanced: advanced.md
  - Contact: contact.md
theme: readthedocs
plugins:
    - encryptcontent:
        title_prefix: ""
        password_button: True
        password_button_text: 'Login'
        remember_password: False # the entered credentials are not saved
        summary: "Password protected page"
        encryption_info_message: "Please enter a password below to access the full Bugg documentation"
        global_password: buggtopsecret
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: True